networks:
  outils.net:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: sae_backend
    ports:
      - "8080:80"

    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=charlymatloc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  db:
    image: mysql:8.0
    container_name: sae_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: charlymatloc
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
